name: Build and Test Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - renovate/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Certifique-se de que está usando a versão correta do Node

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Start application
        run: |
          npm run start &
          sleep 10 # Espera alguns segundos para dar tempo da aplicação iniciar
          curl --fail http://localhost:3333 || exit 1
