name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.8
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
