name: Auto Merge Renovate PRs

on:
  pull_request:
    branches:
      - renovate/**
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Approve PR
        if: ${{ github.event.pull_request.user.login == 'renovate[bot]' }}
        run: gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        if: ${{ github.event.pull_request.user.login == 'renovate[bot]' }}
        run: gh pr merge ${{ github.event.pull_request.number }} --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
